version: '3.7'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    db:
      image: mysql
      user: "1000"